#!/bin/bash
# set up a UFW firewall to redirect traffic from port 8080 to port 80
ufw status | grep -q "Status: active" || ufw enable
ufw allow 80/tcp
ufw allow 8080/tcp
iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
netfilter-persistent save
ufw reload
ufw status verbose
iptables -t nat -L -n -v
